# Inserts a blank line between shell prompts
add_newline = true

# Standard configuration
[character]
success_symbol = "[➜](bold green)" 
error_symbol = "[✗](bold red)"
vimcmd_symbol = '[](bold green)'
vimcmd_replace_one_symbol = '[󰑓](bold yellow)'
vimcmd_visual_symbol = '[](bold yellow)'

# Shell configuration
[shell]
bash_indicator = ""
fish_indicator = "󰈺"
zsh_indicator = ""
powershell_indicator = "󰨊"
unknown_indicator = "mystery shell"
style = "cyan bold"
disabled = false

[python]
symbol = " "

[nodejs]
symbol = " "
detect_files = ['package.json']
detect_folders = ["node_modules"]
detect_extensions = [""]

[rust]
symbol = " "

[java]
symbol = " "

[c]
symbol = " "

